# PANDAS

## Introducing Pandas Objects

- Three fundamental Pandas data structures: *the Series, DataFrame, and Index*.

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data[1]

0.5

In [5]:
data[1:3]

1    0.50
2    0.75
dtype: float64

#### Series as generalized NumPy array

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
    
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:
data['b']

0.5

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7]) # We can even use noncontiguous or nonsequential indices
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

#### Series as specialized dictionary

In [9]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

In [10]:
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [11]:
population['California']

38332521

In [12]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

#### Constructing Series objects

In [13]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [14]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [15]:
pd.Series({2:'a', 1:'b', 3:'c'})
#data can be a dictionary, in which index defaults to the sorted dictionary keys

2    a
1    b
3    c
dtype: object

In [16]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2]) 

3    c
2    a
dtype: object

In [17]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[2, 1]) 

2    a
1    b
dtype: object

### The Pandas DataFrame Object

#### DataFrame as a generalized NumPy array

In [18]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}

In [19]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [20]:
states = pd.DataFrame({'population': population,'area': area})

states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [21]:
states.index 

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [22]:
states.columns

Index(['population', 'area'], dtype='object')

#### DataFrame as specialized dictionary

In [23]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [24]:
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

#### Constructing DataFrame objects
A Pandas DataFrame can be constructed in a variety of ways.<br>
Here we’ll give several examples:

1. From a single Series object

In [25]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

2. From a list of dicts

In [26]:
data = [{'a': i, 'b': 2 * i}
       for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [27]:
 pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

3. From a dictionary of Series objects

In [28]:
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

4. From a two-dimensional NumPy array

In [29]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.900965  0.721018
b  0.984289  0.609298
c  0.757632  0.068729

5. From a NumPy structured array

In [30]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
print(A)

[(0, 0.) (0, 0.) (0, 0.)]


In [31]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

This Index object is an interesting structure in itself, and it can be thought of either as an immutable array or as an ordered set (technically a multiset, as Index objects may contain repeated values).

In [2]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

#### Index as immutable array

In [3]:
ind[1]

3

In [4]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [35]:
print(ind.size, ind.shape, ind.ndim, ind.dtype) 
#Index objects also have many of the attributes familiar from NumPy arrays

5 (5,) 1 int64


#### Index as ordered set

In [5]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [6]:
indA.intersection(indB) #intersection

Int64Index([3, 5, 7], dtype='int64')

In [38]:
indA.union(indB) # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [39]:
print(indA.symmetric_difference(indB))

Int64Index([1, 2, 9, 11], dtype='int64')


## Data Indexing and Selection

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                  index=['a', 'b', 'c', 'd'])

In [8]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
'a' in data

True

In [10]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [44]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

Series objects can even be modified with a dictionary-like syntax. Just as you can 
extend a dictionary by assigning to a new key, you can extend a Series by assigning
to a new index value:

In [45]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### Series as one-dimensional array

- A Series builds on this dictionary-like interface and provides array-style item selection via the same basic mechanisms as NumPy arrays that is, slices, masking, and fancy indexing. Examples of these are as follows:


In [11]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [47]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [48]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [49]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [50]:
c = data[['a', 'e']]
c

a    0.25
e    1.25
dtype: float64

#### Indexers: loc, iloc, and ix

These slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit
Python-style index

In [51]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [52]:
# explicit index when indexing
data[1]

'a'

In [53]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

<div class="alert alert-block alert-danger">
<b>Confusion:</b><br>
 - Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes. <br>
 - These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series.
</div>

1. First, the loc attribute allows indexing and slicing that always references the explicit index:

In [54]:
data.loc[1]

'a'

In [55]:
data.loc[1:3]

1    a
3    b
dtype: object

2. The iloc attribute allows indexing and slicing that always references the implicit Python-style index:

In [56]:
data.iloc[1]

'b'

In [57]:
 data.iloc[1:3]

3    b
5    c
dtype: object

### Data Selection in DataFrame

#### DataFrame as a dictionary

In [13]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})

In [14]:
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})

In [15]:
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

*The individual Series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name:*

In [61]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [62]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

> *ike with the Series objects discussed earlier, this dictionary-style syntax can also be used to modify the object, in this case to add a new column:*

In [16]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### DataFrame as two-dimensiona array

In [64]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [65]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [66]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [14]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [67]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [68]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [69]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [70]:
data.loc[data.density > 100, ]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [71]:
data.loc[data.density > 100, ['pop', 'area']]

pop    area
New York  19651127  141297
Florida   19552860  170312

In [72]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [73]:
data[data.density >= 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [74]:
c = data[data.density > 110]
c

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

## Operating on Data in Pandas

### Ufuncs: Index Preservation

>*Pandas is designed to work with NumPy, any NumPy ufunc will work on Pandas Series and DataFrame objects. Let’s start by defining a simple Series and DataFrame on which to demonstrate this:*

In [17]:
import pandas as pd
import numpy as np

In [19]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [20]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [21]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

### UFuncs: Index Alignment

#### Index alignment in Series

In [23]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [24]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [25]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

>*If using NaN values is not the desired behavior, we can modify the fill value using appropriate object methods in place of the operators.<br> 
For example, calling A.add(B)is equivalent to calling A + B, but allows optional explicit specification of the fill value for any elements in A or B that might be missing:*


In [26]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

#### Index alignment in DataFrame

`A similar type of alignment takes place for both columns and indices when you are performing operations on DataFrames:`

In [27]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [28]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [29]:
list('BAC')

['B', 'A', 'C']

In [30]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [31]:
fill = A.stack().mean()
fill

4.5

In [32]:
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [33]:
A.mean()

A    3.0
B    6.0
dtype: float64

In [35]:
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

### Ufuncs: Operations Between DataFrame and Series

***
> When you are performing operations between a DataFrame and a Series, the index and column alignment is similarly maintained. Operations between a DataFrame and a Series are similar to operations between a two-dimensional and one-dimensional NumPy array. Consider one common operation, where we find the difference of a two-dimensional array and one of its rows:



In [36]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [37]:
A = rng.randint(10, size=(3, 4))
A

array([[1, 9, 8, 9],
       [4, 1, 3, 6],
       [7, 2, 0, 3]])

In [38]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 3, -8, -5, -3],
       [ 6, -7, -8, -6]])

In [39]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  3 -8 -5 -3
2  6 -7 -8 -6

In [41]:
df

Q  R  S  T
0  1  9  8  9
1  4  1  3  6
2  7  2  0  3

In [43]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -8  0 -1  0
1  3  0  2  5
2  5  0 -2  1

In [44]:
halfrow = df.iloc[0, ::2]
halfrow

Q    1
S    8
Name: 0, dtype: int32

In [48]:
halfrow.shape

(2,)

In [45]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  3.0 NaN -5.0 NaN
2  6.0 NaN -8.0 NaN

## Handling Missing Data

> The difference between data found in many tutorials and data in the real world is that real-world data is rarely clean and homogeneous. In particular, many interesting datasets will have some amount of data missing. To make matters even more complicated, different data sources may indicate missing data in different ways.

- In this section, we will discuss some general considerations for missing data, discuss how Pandas chooses to represent it, and demonstrate some built-in Pandas tools for handling missing data in Python. Here and throughout the book, we’ll refer to missing data in general as null, NaN, or NA values.

### Missing Data in Pandas

#### None: Pythonic missing data

In [49]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

#### NaN: Missing numerical data

In [50]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [51]:
1 + np.nan


nan

In [52]:
0 * np.nan

nan

In [53]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [54]:
# NumPy does provide some special aggregations that will ignore these missing values:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

#### NaN and None in Pandas

In [55]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

> NaN and None both have their place, and Pandas is built to handle the two of them
nearly interchangeably, converting between them where appropriate.

In [56]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [57]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

### Operating on Null Values

#### Detecting null values

In [58]:
data = pd.Series([1, np.nan, 'hello', None])

In [59]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [60]:
za = data[data.isnull()]

In [61]:
za

1     NaN
3    None
dtype: object

In [62]:
ze = data[data.notnull()]
ze

0        1
2    hello
dtype: object

#### Dropping null values

In [63]:
data.dropna()

0        1
2    hello
dtype: object

In [64]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

> We cannot drop single values from a DataFrame; we can only drop full rows or full columns. Depending on the application, you might want one or the other, so dropna() gives a number of options for a DataFrame.

In [65]:
#By default, dropna() will drop all rows in which any null value is present:
df.dropna()

0    1  2
1  2.0  3.0  5

- Alternatively, you can drop NA values along a different axis; axis=1 drops all columns containing a null value:

In [67]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [68]:
df.dropna(axis=0)

0    1  2
1  2.0  3.0  5

In [69]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [70]:
df.dropna(axis='rows')

0    1  2
1  2.0  3.0  5

In [71]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [72]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [73]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [76]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [77]:
#We can fill NA entries with a single value, such as zero:
data.fillna(10)

a     1.0
b    10.0
c     2.0
d    10.0
e     3.0
dtype: float64

In [78]:
#We can specify a forward-fill to propagate the previous value forward:
# forward-fill:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [79]:
# we can specify a back-fill to propagate the next values backward:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [80]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [81]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

## Hierarchical Indexing

### A Multiply Indexed Series

#### Pandas MultiIndex

In [2]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
 
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

In [14]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [15]:
pop = pd.Series(populations, index=index)
print(pop)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


In [16]:
# Now to access all data for which the second index is 2010,
#we can simply use the Pandas slicing notation:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

#### MultiIndex as extra dimension

In [17]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

- The **unstack()** method will quickly convert a multiplyindexed Series into a conventionally indexed DataFrame. Naturally, the **stack()** method provides the opposite operation **:)**

In [18]:
 pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [19]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})

In [20]:
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

> In addition, all the ufuncs and other functionality discussed in **“Operating on Data in Pandas”** work with hierarchical indices as well. Here we compute the fraction of people under 18 by year, given the above data:

In [21]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

### Methods of MultiIndex Creation

In [22]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.216396  0.892034
  2  0.736107  0.994940
b 1  0.416500  0.623326
  2  0.126086  0.059754

In [23]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}

In [24]:
ce = pd.Series(data)
ce

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [25]:
ce.unstack()

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

#### Explict MultiIndex constructors

In [26]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [27]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [28]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

#### MultiIndex level names

In [29]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### MultiIndex for columns

In [30]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])

columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'],
                                      ['HR', 'Temp']],
                                     names=['subject', 'type'])

In [31]:
# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

In [33]:
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      55.0  35.6  36.0  36.9  37.0  37.0
     2      21.0  36.5  17.0  37.5  49.0  36.5
2014 1      27.0  37.5  29.0  36.8  43.0  36.6
     2      47.0  38.2  45.0  37.1  47.0  35.2

In [34]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      36.0  36.9
     2      17.0  37.5
2014 1      29.0  36.8
     2      45.0  37.1

### Indexing and Slicing a MultiIndex

#### Multiply indexed Series

In [32]:
 pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [35]:
pop['California', 2000]

33871648

In [36]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [37]:
pop['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [38]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

- selection based on Boolean masks

In [39]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

- Selection based on fancy indexing:

In [40]:
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

#### Multiply indexed DataFrames

In [41]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      55.0  35.6  36.0  36.9  37.0  37.0
     2      21.0  36.5  17.0  37.5  49.0  36.5
2014 1      27.0  37.5  29.0  36.8  43.0  36.6
     2      47.0  38.2  45.0  37.1  47.0  35.2

In [42]:
health_data['Guido', 'HR']

year  visit
2013  1        36.0
      2        17.0
2014  1        29.0
      2        45.0
Name: (Guido, HR), dtype: float64

In [43]:
health_data.iloc[:2, :4]

subject      Bob       Guido      
type          HR  Temp    HR  Temp
year visit                        
2013 1      55.0  35.6  36.0  36.9
     2      21.0  36.5  17.0  37.5

In [44]:
health_data.iloc[1:3, :4]

subject      Bob       Guido      
type          HR  Temp    HR  Temp
year visit                        
2013 2      21.0  36.5  17.0  37.5
2014 1      27.0  37.5  29.0  36.8

In [45]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        55.0
      2        21.0
2014  1        27.0
      2        47.0
Name: (Bob, HR), dtype: float64

### Rearranging Multi-Indices

> One of the keys to working with multiply indexed data is knowing how to effectively transform the data. There are a number of operations that will preserve all the information in the dataset, but rearrange it for the purposes of various computations. We
saw a brief example of this in the stack() and unstack() methods, but there are many more ways to finely control the rearrangement of data between hierarchical indices and columns, and we’ll explore them here.

#### Sorted and unsorted indices

In [46]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.521899
      2      0.194394
c     1      0.784488
      2      0.793734
b     1      0.668003
      2      0.973753
dtype: float64

In [47]:
data = data.sort_index()
data

char  int
a     1      0.521899
      2      0.194394
b     1      0.668003
      2      0.973753
c     1      0.784488
      2      0.793734
dtype: float64

In [48]:
data['a':'b']

char  int
a     1      0.521899
      2      0.194394
b     1      0.668003
      2      0.973753
dtype: float64

#### Stacking and unstacking indices

In [49]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [50]:
pop.unstack(level=1)


year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

`The opposite` of **unstack() is stack()**, which here can be used to recover the original series:

In [51]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### Index setting and resetting

Another way to rearrange hierarchical data is to turn the index labels into columns; this can be accomplished with the reset_index method. Calling this on the population dictionary will result in a DataFrame with a state and year column holding the information that was formerly in the index. For clarity, we can optionally specify the name of the data for the column representation:

In [52]:
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

Often when you are working with data in the real world, the raw input data looks like this and it’s useful to build a MultiIndex from the column values. This can be done with the set_index method of the DataFrame, which returns a multiply indexed DataFrame:

In [53]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

### Data Aggregations on Multi-Indices

In [54]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      55.0  35.6  36.0  36.9  37.0  37.0
     2      21.0  36.5  17.0  37.5  49.0  36.5
2014 1      27.0  37.5  29.0  36.8  43.0  36.6
     2      47.0  38.2  45.0  37.1  47.0  35.2

> Perhaps we’d like to average out the measurements in the two visits each year. We can do this by naming the index level we’d like to explore, in this case the year:

In [57]:
data_mean = health_data.groupby(level='year').mean()
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     38.0  36.05  26.5  37.20  43.0  36.75
2014     37.0  37.85  37.0  36.95  45.0  35.90

In [58]:
data_mean1 = health_data.groupby(level='year').median()
data_mean1

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     38.0  36.05  26.5  37.20  43.0  36.75
2014     37.0  37.85  37.0  36.95  45.0  35.90

> By further making use of the axis keyword, we can take the mean among levels on the columns as well:

In [60]:
data_mean.groupby(axis = 1, level="type").mean()

type         HR       Temp
year                      
2013  35.833333  36.666667
2014  39.666667  36.900000

<div class="alert alert-block alert-info">
<b>Median and Mean</b>:)<br>
    Jereo tsara ny difference entre izy roa .
</div>

## Combining Datasets: Concat and Append

In [2]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

In [3]:
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

### Recall: Concatenation of NumPy Arrays

In [4]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

### Simple Concatenation with pd.concat

In [6]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [7]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1); print(df2); print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [8]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3); print(df4); print(pd.concat([df3, df4], axis='columns'))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [9]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3); print(df4); print(pd.concat([df3, df4], axis='rows'))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1


#### Duplicate indices

> One important difference between **np.concatenate and pd.concat** is that Pandas concatenation preserves indices, even if the result will have duplicate indices! Consider this simple example:

In [10]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

In [11]:
y.index = x.index # make duplicate indices!
print(x); print(y); print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


#### Adding MultiIndex keys

In [12]:
print(x); print(y); print(pd.concat([x, y], keys=['x', 'y']))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3


#### Concatenation with joins

In [13]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5); print(df6); print(pd.concat([df5, df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


In [14]:
print(df5); print(df6);
print(pd.concat([df5, df6], join='inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [15]:

print(pd.concat([df5, df6], join='outer'))

     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


>inner (intersect) <br> outer (union)

#### The append() method

In [16]:
print(df1); print(df2); print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


C:\Users\PERSONNE\AppData\Local\Temp\ipykernel_3844\1561387783.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df1); print(df2); print(df1.append(df2))


In [20]:
print(df1); print(df2); print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


<div class="alert alert-block alert-danger">
<b>Aty ny maso:</b> <br>
    Tsy dia tena tsara ny mampiasa anio methode append io fa aleo mampiasa ny pandas concatenation ihany.
</div>

## Combining Datasets: Merge and Join

### Relational Algebra
- The behavior implemented in pd.merge() is a subset of what is known as relational algebra, which is a formal set of rules for manipulating relational data, and forms the conceptual foundation of operations available in most databases.
-  The strength of the relational algebra approach is that it proposes several primitive operations, which become the building blocks of more complicated operations on any dataset. With this lexicon of fundamental operations implemented efficiently in a database or other program, a wide range of fairly complicated composite operations can be performed.
- Pandas implements several of these fundamental building blocks in the pd.merge() function and the related join() method of Series and DataFrames. As we will see, these let you efficiently link data from different sources.
